### PR TITLE
I will create a PR on 1st ocgt

### PR DESCRIPTION
**Pull request by toukirkhan**
Made the changes and added files according to requirements of readme please add me.

### CODE REVIEW

**Comment by ossamamehmood** [comment]
Reopen your PR to get entertain

**Comment by toukirkhan** [comment]
Yeah but I will open the PR on 1st oct

**Comment by toukirkhan** [comment]
Else I won't get the valid pr for hacktoberfest

**Comment by ossamamehmood** [comment]
Sure

**Pull request closed without merging**
